version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
        POSTGRES_USER: paperless_user
        POSTGRES_PASSWORD: paperless_pw
        POSTGRES_DB: paperlessdb
    ports:
      - '5455:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: